progress:
  '#changed': 1511354115
  '#changed_by': '1'
  '#completed_items': 7
  '#items':
    install_and_enable_seo_checklist_module:
      '#completed': 1511354115
      '#uid': '1'
    install_and_enable_coffee_module:
      '#completed': 1511354115
      '#uid': '1'
    configure_coffee_module:
      '#completed': 1511354115
      '#uid': '1'
    install_and_enable_admin_toolbar_module:
      '#completed': 1511354115
      '#uid': '1'
    install_composer_command_line_tool:
      '#completed': 1511354115
      '#uid': '1'
    install_drush_command_line_tool:
      '#completed': 1511354115
      '#uid': '1'
    show_cli_commands:
      '#completed': 1511354115
      '#uid': '1'
