module:
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  better_exposed_filters: 0
  block: 0
  block_content: 0
  bootstrap_paragraphs: 0
  breakpoint: 0
  checklistapi: 0
  ckeditor: 0
  classy_paragraphs: 0
  coffee: 0
  color: 0
  comment: 0
  conditional_fields: 0
  config: 0
  contact: 0
  custhtml: 0
  datetime: 0
  dblog: 0
  devel: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  hierarchical_taxonomy_menu: 0
  history: 0
  image: 0
  kint: 0
  link: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  paragraphs_accordion: 0
  paragraphs_tabs: 0
  path: 0
  range: 0
  rdf: 0
  request: 0
  search: 0
  seo_checklist: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  taxonomy_menu: 0
  text: 0
  text_with_title: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_ui: 0
  viewsreference: 0
  webprofiler: 0
  menu_link_content: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  bootstrap: 0
  ltk: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
